name: E2E YC Tests

on:
  workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      
      - name: Run E2E YC Tests
        run: echo "Running Test"
